### ISSUE TITLE
Unable to print other Bot messages

### ISSUE THREAD

**Issue by warmfusion** [warmfusion/Tilly-The-Printerbot#5]
Messages from other Bots (eg GitLabBot) aren't printing as bots don't appear to have real names, so the `msgUser['name']` throws an error.

Seems easy enough to resolve... if the code wasn't a horror

**Comment by warmfusion** [comment]
```
undefined method `[]' for nil:NilClass
/usr/local/bin/printerbot:157:in `process_reaction_event'
/usr/local/bin/printerbot:86:in `block in start!'
/var/lib/gems/2.1.0/gems/slack-ruby-client-0.8.0/lib/slack/real_time/client.rb:188:in `call'
/var/lib/gems/2.1.0/gems/slack-ruby-client-0.8.0/lib/slack/real_time/client.rb:188:in `block in run_callbacks'
/var/lib/gems/2.1.0/gems/slack-ruby-client-0.8.0/lib/slack/real_time/client.rb:187:in `each'
```

**Comment by warmfusion** [comment]
Further investigation, and setting msgUser to be the name of the userID helped, but highlighted that bots often send their messages as 'attachments'...

So i think a big refactor might be worthwhile to clean up the message handling itself
